package com.rtzan.drools

import com.rtzan.drools.model.*
 
rule "Group_01_Rule_01"
    agenda-group "Group_01"
	when
		testObject : TestObject()
	then
	    System.out.println("Group_01_Rule_01 just fired for " + testObject);
		
end

rule "Group_02_Rule_01"
    agenda-group "Group_02"
	when
		testObject : TestObject()
	then
		System.out.println("Group_02_Rule_01 just fired for " + testObject);
end

rule "Group_02_Rule_02"
    agenda-group "Group_02"
	when
		testObject : TestObject()
	then
		System.out.println("Group_02_Rule_01 just fired for " + testObject);
end

query "FindClassNameStartingWith" (Class theClass)
    object: Object(class == theClass)
end