package com.rtzan.drools

import com.rtzan.drools.model.*
 
rule "Rule_01" salience -1
    when
        customer : Customer( flagged == false && hasProductsInCart() == true && name str[startsWith] "ana_0" )
    then
        System.out.println("\t> Rule_01 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
        
end

rule "Rule_02" salience -2
    when
        customer : Customer( flagged == false && hasProductsInCart() == true && name str[startsWith] "a"  )
    then
        System.out.println("\t> Rule_02 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
end

rule "Rule_03" salience -3
    when
        customer : Customer( flagged == false && hasProductsInCart() == true && name str[endsWith] "10" )
    then
        System.out.println("\t> Rule_03 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
        
end

rule "Rule_04" salience -4
    when
        customer : Customer( flagged == false && hasProductsInCart() == true && name str[startsWith] "ana_"  )
    then
        System.out.println("\t> Rule_04 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
end

rule "Rule_05" salience -5
    when
        customer : Customer( flagged == false && hasProductsInCart() == false && name str[startsWith] "ana_" )
    then
        System.out.println("\t> Rule_05 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
        
end

rule "Rule_06" salience -6
    when
        customer : Customer( flagged == false && hasProductsInCart() == false && name str[startsWith] "ana_" )
    then
        System.out.println("\t> Rule_06 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
        
end

