package com.rtzan.drools

import com.rtzan.drools.model.*
 
rule "Group_01_Rule_01"
    agenda-group "Group_01"
    when
        customer : Customer( flagged == false && hasProductsInCart() == true && name str[startsWith] "ana_0" )
    then
        System.out.println("\t> Group_01_Rule_01 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
        
end

rule "Group_02_Rule_01"
    agenda-group "Group_02"
    when
        customer : Customer( flagged == false && hasProductsInCart() == true && name str[startsWith] "ana_"  )
    then
        System.out.println("\t> Group_02_Rule_01 just fired for " + customer);
        customer.setFlagged(true);
end

rule "Group_02_Rule_02"
    agenda-group "Group_02"
    when
        customer : Customer( flagged == false && hasProductsInCart() == false && name str[startsWith] "ana_1" )
    then
        System.out.println("\t> Group_02_Rule_02 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
end







query "FindClassNameStartingWith" (Class theClass)
    object: Object(class == theClass)
end

query "FindFlaggedCustomers"
    customer: Customer( flagged == true )
end
