package com.rtzan.drools

import com.rtzan.drools.model.*
 
rule "Group_01_Rule_01"
    agenda-group "Group_01"
    when
        customer : Customer( flagged == false && hasProductsInCart() == true && name str[startsWith] "ana_0" )
    then
        System.out.println("\t> Group_01_Rule_01 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
        
end

rule "Group_02_Rule_01"
    agenda-group "Group_02"
    when
        customer : Customer( flagged == false && hasProductsInCart() == true && name str[startsWith] "a"  )
    then
        System.out.println("\t> Group_02_Rule_01 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
end

rule "Group_03_Rule_01"
    agenda-group "Group_03"
    when
        customer : Customer( flagged == false && hasProductsInCart() == true && name str[endsWith] "10" )
    then
        System.out.println("\t> Group_03_Rule_01 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
        
end

rule "Group_04_Rule_01"
    agenda-group "Group_04"
    when
        customer : Customer( flagged == false && hasProductsInCart() == true && name str[startsWith] "ana_"  )
    then
        System.out.println("\t> Group_04_Rule_01 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
end

rule "Group_05_Rule_01"
    agenda-group "Group_05"
    when
        customer : Customer( flagged == false && hasProductsInCart() == false && name str[startsWith] "ana_" )
    then
        System.out.println("\t> Group_05_Rule_01 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
        
end

rule "Group_06_Rule_01"
    agenda-group "Group_06"
    when
        customer : Customer( flagged == false && hasProductsInCart() == false && name str[startsWith] "ana_" )
    then
        System.out.println("\t> Group_06_Rule_01 just fired for " + customer + " == FLAG");
        customer.setFlagged(true);
        
end

